# DS-7331 Mini Lab - Logistic Regression and SVMs

### By Ahmad Salama, Titus Karuri, Eman Meraj, Sue Camara

In [8]:
# ---------------------------------------------------------
# Python Library Setup: Check and Install Required Dependencies
# ---------------------------------------------------------
import sys
import subprocess
import importlib.util as imp_util

# List of required libraries\packages for this notebook
required_packages = [
    "pandas",
    "missingno",
    "seaborn",
    "matplotlib",
    "math",
    "scikit-learn",
    "numpy",
    "sklearn LogisticRegression",
    "sklearn metrics"

]

for package in required_packages:
    # iterate over the required packages and if any is not installed, trigger a pip command
    # to install.
    if imp_util.find_spec(package) is None:
        print(f"Package '{package}' is not installed. Installing now...")
        # run the pip command
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", package],
            stdout=subprocess.DEVNULL
        )
        print(f"Package '{package}' installed successfully.\n")
    else:
        print(f"Package '{package}' is already installed.\n")

# ---------------------------------------------------------
# Import required libraries\packages
# ---------------------------------------------------------
import csv as csv
import pandas as pd
import numpy as np
import missingno as msno
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import math
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn import datasets as ds
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics as mt


Package 'pandas' is already installed.

Package 'missingno' is already installed.

Package 'seaborn' is already installed.

Package 'matplotlib' is already installed.

Package 'math' is already installed.

Package 'sklearn' is already installed.

Package 'numpy' is already installed.



In [41]:
# dataset file name
DATASET_NAME = "default_of_credit_card_clients.csv"

# load the dataset
df = pd.read_csv(DATASET_NAME, header=1)
df.info

<bound method DataFrame.info of           ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  

In [42]:

unique = df["default payment next month"].unique()
print(unique)

[1 0]


In [45]:
education=df["EDUCATION"].unique()
print(education)


[2 1 3 4]


In [44]:
df= df[df["EDUCATION"].isin([1,2,3,4])]


In [48]:
marriage = df["MARRIAGE"].unique()
print(marriage)

[1 2 3]


In [47]:
df = df[df["MARRIAGE"].isin([1,2,3])]

In [49]:
# Split into train/test while preserving the class balance in the target
target = "default payment next month"
# Define the target vector
y = df[target].astype(int)
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=[target]),
    y,
    test_size=0.2, # 20% held out for testing
    random_state=0, # reproducible split
    stratify=y
)

# Overall default rate in the TRAIN set
global_mean = y_train.mean()

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as msno

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn import metrics


In [6]:
import os
os.getcwd()


'C:\\Users\\sueca\\OneDrive\\Desktop\\time series'

In [3]:
import os
os.chdir(r"C:\Users\sueca\OneDrive\Desktop\time series")
os.getcwd()


'C:\\Users\\sueca\\OneDrive\\Desktop\\time series'

In [7]:
df = pd.read_csv("default_of_credit_card_clients.csv", header=1)
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_A

In [10]:
# Clean category values
df = df[df["EDUCATION"].isin([1, 2, 3, 4])]
df = df[df["MARRIAGE"].isin([1, 2, 3])]

# Define target and predictors
target = "default payment next month"
y = df[target].astype(int)
X = df.drop(columns=[target])

# Train / test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0,
    stratify=y
)

print("Training default rate:", y_train.mean())


Training default rate: 0.2231418918918919


In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# 1) Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# 2) Fit logistic regression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled, y_train)

# 3) Predict class + probability
y_pred = log_reg.predict(X_test_scaled)
y_prob = log_reg.predict_proba(X_test_scaled)[:, 1]

# 4) Evaluate
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", metrics.confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", metrics.classification_report(y_test, y_pred))
print("ROC AUC:", metrics.roc_auc_score(y_test, y_prob))


Accuracy: 0.813882790069245
Confusion Matrix:
 [[4490  110]
 [ 992  329]]

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.98      0.89      4600
           1       0.75      0.25      0.37      1321

    accuracy                           0.81      5921
   macro avg       0.78      0.61      0.63      5921
weighted avg       0.80      0.81      0.78      5921

ROC AUC: 0.7348151927064478


In [13]:
# Our model does a good job at predicting credit card behavior and shows that about 22% of customers in the data actually default. In addition, this model also improves on this by correctly classifying about 81% of customers, which shows the model is learning meaningful patterns rather than guessing. So, when the model predicts that someone will default, it is usually correct, meaning it prioritizes avoiding false alarms over catching every risky case. Overall, the model is useful as a starting point for credit risk prediction, but it could be improved to identify more high-risk customers. This type of trade-off is common in financial risk models and can be adjusted depending on business needs.

In [22]:
# ========================
# Support Vector Machine 
# ========================

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

# Scale features 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# Train SVM with linear kernel
svm_model = SVC(kernel="linear", C=1.0, probability=True, random_state=0)
svm_model.fit(X_train_scaled, y_train)

# Predictions
svm_pred = svm_model.predict(X_test_scaled)
svm_prob = svm_model.predict_proba(X_test_scaled)[:, 1]

# Evaluation
print("=== SVM (Linear Kernel) Results ===")
print("Accuracy:", metrics.accuracy_score(y_test, svm_pred))
print("Confusion Matrix:\n", metrics.confusion_matrix(y_test, svm_pred))
print("\nClassification Report:\n", metrics.classification_report(y_test, svm_pred))
print("ROC AUC:", metrics.roc_auc_score(y_test, svm_prob))


=== SVM (Linear Kernel) Results ===
Accuracy: 0.813882790069245
Confusion Matrix:
 [[4495  105]
 [ 997  324]]

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.98      0.89      4600
           1       0.76      0.25      0.37      1321

    accuracy                           0.81      5921
   macro avg       0.79      0.61      0.63      5921
weighted avg       0.80      0.81      0.77      5921

ROC AUC: 0.7069736365730837


In [ ]:
# ============================
# SVM Parameter Adjustment 
# ============================

from sklearn.svm import SVC
from sklearn import metrics

C_values = [0.01, 0.1, 1, 10, 100]

best_C = None
best_auc = -1

print("=== Linear SVM Tuning (C values) ===")
for C in C_values:
    svm_tuned = SVC(kernel="linear", C=C, probability=True, random_state=0)
    svm_tuned.fit(X_train_scaled, y_train)

    pred = svm_tuned.predict(X_test_scaled)
    prob = svm_tuned.predict_proba(X_test_scaled)[:, 1]

    acc = metrics.accuracy_score(y_test, pred)
    auc = metrics.roc_auc_score(y_test, prob)

    print(f"C={C:<6}  Accuracy={acc:.3f}  ROC_AUC={auc:.3f}")

    if auc > best_auc:
        best_auc = auc
        best_C = C

print(f"\nBest C based on ROC AUC: {best_C} (ROC AUC = {best_auc:.3f})")


=== Linear SVM Tuning (C values) ===
C=0.01    Accuracy=0.814  ROC_AUC=0.707
C=0.1     Accuracy=0.814  ROC_AUC=0.708
C=1       Accuracy=0.814  ROC_AUC=0.707


In [8]:
#Even though both models achieved similar accuracy, logistic regression offered a slightly better overall predictive performance, which includes a higher ROC/AUC that trained more efficiently, and was easier to explain, making it the better choice for this dataset and task. The SVM was competitive but did not outperform logistic regression here and is less interpretable.

In [9]:
import pandas as pd
import matplotlib.pyplot as plt

# Manually store results you already computed
results = pd.DataFrame({
    "Model": ["Logistic Regression", "SVM (Linear)"],
    "Accuracy": [0.8139, 0.8139],
    "ROC AUC": [0.7348, 0.7069]
})

results


Model  Accuracy  ROC AUC
0  Logistic Regression    0.8139   0.7348
1         SVM (Linear)    0.8139   0.7069

In [12]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Define target and predictors
target = "default payment next month"
y = df[target].astype(int)
X = df.drop(columns=[target])

# Train / test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0, stratify=y
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

# Train logistic regression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled, y_train)

# Create feature importance table
coef_table = pd.DataFrame({
    "Feature": X_train.columns,
    "Weight": log_reg.coef_[0],
    "Importance": np.abs(log_reg.coef_[0])
}).sort_values("Importance", ascending=False)

coef_table.head(10)


Feature    Weight  Importance
6       PAY_0  0.638714    0.638714
12  BILL_AMT1 -0.458673    0.458673
18   PAY_AMT1 -0.281820    0.281820
13  BILL_AMT2  0.215247    0.215247
19   PAY_AMT2 -0.176589    0.176589
14  BILL_AMT3  0.157850    0.157850
7       PAY_2  0.103575    0.103575
15  BILL_AMT4 -0.101957    0.101957
20   PAY_AMT3 -0.098118    0.098118
1   LIMIT_BAL -0.098089    0.098089

In [13]:
#The model places the greatest importance on recent payment behavior and balance information, indicating that how customers manage their debt over time is far more predictive of default than basic account characteristics.

In [16]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

# Recreate X and y 
target = "default payment next month"
y = df[target].astype(int)
X = df.drop(columns=[target])

# Train/test split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0, stratify=y
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

# Re-train SVM (linear)
svm_model = SVC(kernel="linear", C=1.0, probability=True, random_state=0)
svm_model.fit(X_train_scaled, y_train)

# ---- Inspect support vectors ----
print("Number of support vectors per class:", svm_model.n_support_)

sv_idx = svm_model.support_
support_vectors_df = X_train.iloc[sv_idx]

support_vectors_df.head(10)


Number of support vectors per class: [6402 5242]


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
16218  16219     120000    2          1         2   45      0      0      0   
1771    1772      50000    2          3         1   56      0      0      0   
26498  26499      50000    2          3         1   52      0      0      0   
644      645      30000    2          2         1   31      0      0      2   
631      632      50000    2          2         2   23      0      0      0   
19976  19977     210000    2          1         2   32      1     -2     -1   
20859  20860      80000    1          2         1   39      0      0      0   
2916    2917      20000    1          3         2   26      8      7      6   
25055  25056     240000    1          5         1   50      0      0      0   
28783  28784      20000    2          3         2   44      0      0      0   

       PAY_4  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
16218      0  ...      87941      89737      95451      97379      3079   
1771       0  ...      28913      29093      29306      29506      2407   
26498      0  ...      38085          0      10400          0      2035   
644        0  ...      18782      19006      19637      21251      3200   
631        0  ...      29284      30487      33831      33138      2000   
19976     -1  ...      20363        770          0       6138         0   
20859      0  ...      78545      19212      36800      18900      5107   
2916       5  ...      35381      31539      27409      23567         0   
25055      0  ...     235353     240001     190904     193710      9560   
28783      0  ...      14561      15017      15119       4077      1230   

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
16218      3185      3251      7200      3600      3900  
1771       2960      1029      1059      1073      1200  
26498      1650         0     10400         0         0  
644           0       742      1000      2000         0  
631        2000      2000      4000         0      2000  
19976     21337       770         0      6138         0  
20859      3269      1400       368      1000         0  
2916          0         0         0         0       300  
25055      9000      8790      8013      8125      8000  
28783      1354      1200       302        82        83  

[10 rows x 24 columns]